name: Blog Posts

on:
#   push:
#     branches: 
#       - master 

  schedule:
    # 每12小时执行一次
    - cron: "0 */12 * * *"

jobs:
  update-readme-with-blog:
    name: Load My Blog Post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://www.seaepoch.com/atom.xml"
          
      # ⏱️ Google PageSpeed
      - name: Screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: assets/pagespeed.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.seaepoch.com/
